// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAmnOfgkA7ESn4v8C9ADOY2LBA48SyTQg',
    appId: '1:103431719923:web:a7607627b7e25d844e6086',
    messagingSenderId: '103431719923',
    projectId: 'more-app-d670d',
    authDomain: 'more-app-d670d.firebaseapp.com',
    storageBucket: 'more-app-d670d.firebasestorage.app',
    measurementId: 'G-7MMBMYG5J1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG7xL4Ls1yU2kMJJjIrscs24Tuw4w9PDQ',
    appId: '1:103431719923:android:61ba0fd46b2115c14e6086',
    messagingSenderId: '103431719923',
    projectId: 'more-app-d670d',
    storageBucket: 'more-app-d670d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbQU7ScsfQbLSfWuNz1Of4dhMwcdTgGwE',
    appId: '1:103431719923:ios:4940b52ec68aba7c4e6086',
    messagingSenderId: '103431719923',
    projectId: 'more-app-d670d',
    storageBucket: 'more-app-d670d.firebasestorage.app',
    iosBundleId: 'com.example.moreIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbQU7ScsfQbLSfWuNz1Of4dhMwcdTgGwE',
    appId: '1:103431719923:ios:4940b52ec68aba7c4e6086',
    messagingSenderId: '103431719923',
    projectId: 'more-app-d670d',
    storageBucket: 'more-app-d670d.firebasestorage.app',
    iosBundleId: 'com.example.moreIn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAmnOfgkA7ESn4v8C9ADOY2LBA48SyTQg',
    appId: '1:103431719923:web:c2385604ffde072b4e6086',
    messagingSenderId: '103431719923',
    projectId: 'more-app-d670d',
    authDomain: 'more-app-d670d.firebaseapp.com',
    storageBucket: 'more-app-d670d.firebasestorage.app',
    measurementId: 'G-1CPMG2CE0H',
  );
}
